name: 💬 Question
description: Ask a question about using Bemanning
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out the form below.
        
        **Note**: For general discussions, consider using [GitHub Discussions](../../discussions) instead.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried.
      placeholder: I've tried... I'm working on...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information that might help us answer your question.
      placeholder: Screenshots, error messages, etc.
